#!/usr/bin/env python3
"""
Togithub scan script: scan a project directory for things to clean up before
pushing to GitHub. Outputs JSON to stdout.

Categories:
  1. ai_trace_files      — files/dirs that look like AI/dev process artifacts
  2. ai_trace_content    — lines in code/docs containing AI attribution
  3. privacy_patterns    — personal info / secrets / local paths / org names
  4. dangerous_files     — large files, secrets, .env, .pem, etc.

Usage:
  python scan.py <project_root> [--exclude <glob>]...

Exit code: 0 always (parseable JSON, no findings = empty arrays).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, asdict, field
from pathlib import Path
from typing import Iterable

# --------------------------------------------------------------------------- #
# Config
# --------------------------------------------------------------------------- #

# Skip these directories entirely.
SKIP_DIRS = {
    ".git", "node_modules", "__pycache__", ".venv", "venv", "env",
    "dist", "build", "target", ".next", ".nuxt", ".output",
    "vendor", "Pods", ".gradle", ".idea", ".vscode",
    ".mypy_cache", ".pytest_cache", ".ruff_cache", ".tox",
    "Library", "DerivedData",  # macOS / Xcode
    "bin", "obj",  # .NET
}

# File extensions to scan for content patterns.
SCANNABLE_EXTS = {
    ".py", ".js", ".ts", ".tsx", ".jsx", ".mjs", ".cjs",
    ".go", ".rs", ".java", ".kt", ".swift", ".c", ".cpp", ".h", ".hpp",
    ".rb", ".php", ".cs", ".scala", ".sh", ".bash", ".zsh", ".ps1",
    ".html", ".css", ".scss", ".vue", ".svelte", ".astro",
    ".md", ".rst", ".txt", ".adoc",
    ".json", ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf",
    ".sql", ".graphql", ".proto",
    ".env", ".envrc",
    "Dockerfile", "Makefile", "Rakefile", "Gemfile",
    ".gitignore", ".dockerignore",
}

# Max file size to scan for content (10 MB).
MAX_SCAN_BYTES = 10 * 1024 * 1024

# Large file threshold for warning (10 MB).
LARGE_FILE_BYTES = 10 * 1024 * 1024

# --------------------------------------------------------------------------- #
# Patterns
# --------------------------------------------------------------------------- #

AI_TRACE_FILE_PATTERNS = [
    re.compile(r"^\.?claude/?$"),
    re.compile(r"^task_plan\.md$", re.IGNORECASE),
    re.compile(r"^findings\.md$", re.IGNORECASE),
    re.compile(r"^progress\.md$", re.IGNORECASE),
    re.compile(r"^NOTES?\.md$", re.IGNORECASE),
    re.compile(r"^SCRATCH.*\.md$", re.IGNORECASE),
    re.compile(r"^TODO.*\.md$", re.IGNORECASE),
    re.compile(r"^RETRO.*\.md$", re.IGNORECASE),
    re.compile(r"^CLAUDE\.md$", re.IGNORECASE),
    re.compile(r"^AGENTS\.md$", re.IGNORECASE),
    re.compile(r"^\.cursorrules$"),
    re.compile(r"^\.windsurfrules$"),
    re.compile(r"^\.aider.*"),
    re.compile(r"^\.github/copilot-instructions\.md$"),
    re.compile(r"^\.continue/.*"),
    re.compile(r"^\.devcontainer/.*"),
]

DANGEROUS_FILE_PATTERNS = [
    re.compile(r"^\.env$"),
    re.compile(r"^\.env\..+"),
    re.compile(r"^\.envrc$"),
    re.compile(r"^credentials\.json$"),
    re.compile(r"^secrets?\.(json|ya?ml|toml|env)$"),
    re.compile(r".*\.pem$"),
    re.compile(r".*\.key$"),
    re.compile(r".*\.p12$"),
    re.compile(r".*\.pfx$"),
    re.compile(r"^id_rsa.*"),
    re.compile(r"^id_ed25519.*"),
    re.compile(r".*\.keystore$"),
    re.compile(r"^service-account.*\.json$"),
]

AI_CONTENT_PATTERNS = [
    (re.compile(r"Co-Authored-By:\s*Claude", re.IGNORECASE), "ai-attribution"),
    (re.compile(r"Generated with \[?Claude", re.IGNORECASE), "ai-attribution"),
    (re.compile(r"Generated by Claude", re.IGNORECASE), "ai-attribution"),
    (re.compile(r"由\s*Claude\s*生成", re.IGNORECASE), "ai-attribution"),
    (re.compile(r"由\s*AI\s*生成", re.IGNORECASE), "ai-attribution"),
    (re.compile(r"claude\.com/claude-code", re.IGNORECASE), "ai-attribution"),
    (re.compile(r"<system-reminder>", re.IGNORECASE), "ai-leak"),
    (re.compile(r"<command-(message|name|args)>", re.IGNORECASE), "ai-leak"),
    (re.compile(r"🤖.*Generated", re.IGNORECASE), "ai-attribution"),
]

# Email whitelist: addresses that are not real personal emails.
# - Reserved TLDs (RFC 6761/2606): .example .test .invalid .localhost
# - Reserved example domains
# - Specific no-reply addresses
SAFE_EMAIL_TLDS = {".example", ".test", ".invalid", ".localhost"}
SAFE_EMAIL_DOMAINS = {"example.com", "example.org", "example.net", "test.com"}
SAFE_EMAIL_FULL = {"noreply@github.com"}
# Placeholder local parts that, on GitHub platform domains, are not real
# personal emails (e.g. commit-bot noreply addresses).
SAFE_EMAIL_PLACEHOLDER_LOCALS = {
    "user", "foo", "bar", "your-email", "your.email", "email",
    "test", "example", "admin", "noreply",
}
SAFE_EMAIL_GITHUB_DOMAINS = {"github.com", "users.noreply.github.com"}


def _is_safe_email(addr: str) -> bool:
    """Return True if addr is a placeholder/example email that should not be reported."""
    addr = addr.strip().lower()
    if addr in SAFE_EMAIL_FULL:
        return True
    if "@" not in addr:
        return False
    local, _, domain = addr.rpartition("@")
    # reserved TLD
    for tld in SAFE_EMAIL_TLDS:
        if domain.endswith(tld):
            return True
    if domain in SAFE_EMAIL_DOMAINS:
        return True
    if domain in SAFE_EMAIL_GITHUB_DOMAINS and local in SAFE_EMAIL_PLACEHOLDER_LOCALS:
        return True
    return False


# Placeholder usernames in example local paths.
SAFE_PATH_USERS = {
    "user", "username", "user-name", "alice", "bob", "foo", "bar",
    "yourname", "your-name", "name", "project", "app", "home",
    "example", "default", "guest", "admin", "test",
}


def _is_safe_path_user(m: re.Match) -> bool:
    """True if the matched local path's user segment is a placeholder."""
    try:
        user = m.group(1).lower()
    except (IndexError, AttributeError):
        return False
    return user in SAFE_PATH_USERS


# Default-gateway / generic private IPs that are textbook examples, not leaks.
SAFE_PRIVATE_IPS = {"192.168.0.1", "192.168.1.1", "10.0.0.1", "10.0.0.2"}


def _is_safe_private_ip(ip_str: str) -> bool:
    return ip_str in SAFE_PRIVATE_IPS


PRIVACY_PATTERNS = [
    ("email", re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b")),
    # CN mobile: optional +86 prefix, optional spaces/dashes between groups
    ("phone-cn", re.compile(
        r"(?:(?<!\d)\+?86[\s\-]?)?(?<!\d)1[3-9]\d(?:[\s\-]?\d){8}(?!\d)"
    )),
    ("phone-landline-cn", re.compile(
        r"(?<!\d)0\d{2,3}[\s\-]?\d{7,8}(?!\d)"
    )),
    ("id-card-cn", re.compile(
        r"(?<!\d)[1-9]\d{5}(?:18|19|20)\d{2}(?:0\d|1[0-2])(?:[0-2]\d|3[01])\d{3}[\dXx](?!\d)"
    )),
    # bank-card: 16-19 digits, but not hex (UUID/SHA), not all-same-digit.
    # The all-same-digit check is done in scan_line() since lookahead position
    # makes pure regex unreliable here.
    ("bank-card", re.compile(
        r"(?<![\dA-Fa-f])\d{16,19}(?![\dA-Fa-f])"
    )),
    ("api-key", re.compile(
        r"(?i)(api[_-]?key|secret|token|password|passwd|pwd|access[_-]?key|auth[_-]?token)"
        r"\s*[:=]\s*['\"]?([A-Za-z0-9_\-/+=]{16,})['\"]?"
    )),
    ("local-path-win", re.compile(r"[A-Z]:\\Users\\([\w\-\. ]+)\\", re.IGNORECASE)),
    ("local-path-unix", re.compile(r"/(?:Users|home)/([\w\-\. ]+)/")),
    ("home-tilde", re.compile(r"~/\.?(?:ssh|aws|config|gnupg)/[\w\-\.]+")),
    # 127.x is loopback (not leakable), 10/172.16-31/192.168 are RFC1918 private
    ("ipv4-private", re.compile(
        r"\b(?:10\.\d{1,3}\.\d{1,3}\.\d{1,3}"
        r"|192\.168\.\d{1,3}\.\d{1,3}"
        r"|172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3})\b"
    )),
    ("ipv6-private", re.compile(
        r"\b(?:fc|fd)[0-9a-f]{2}:[0-9a-f:]+/?[0-9a-f]*(?!\w)"
        r"|\bfe[89ab][0-9a-f]:[0-9a-f:]+/?[0-9a-f]*\b",
        re.IGNORECASE
    )),
    ("geo-coord", re.compile(
        r"(?i)(?:lat|latitude|lng|longitude)\s*[:=]\s*-?\d{1,3}\.\d{2,}"
    )),
    # ---- Cloud & service API keys (all danger) ----
    ("jwt", re.compile(r"\beyJ[A-Za-z0-9_\-]+\.eyJ[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+\b")),
    ("aws-key", re.compile(r"\b(?:AKIA|ASIA)[A-Z0-9]{16}\b")),
    ("github-token", re.compile(r"\bgh[pousr]_[A-Za-z0-9]{36,}\b")),
    ("aliyun-key", re.compile(r"\bLTAI[A-Za-z0-9]{12,}\b")),         # 阿里云 AccessKey
    ("tencent-key", re.compile(r"\bAKID[A-Za-z0-9]{16,}\b")),        # 腾讯云 SecretId
    ("huawei-key", re.compile(r"\b(?:AKSK|HW)[A-Z0-9]{16,}\b")),     # 华为云 AccessKey
    ("stripe-live", re.compile(r"\bsk_live_[A-Za-z0-9]{20,}\b")),
    ("stripe-test", re.compile(r"\bsk_test_[A-Za-z0-9]{20,}\b")),
    ("slack-token", re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}\b")),
    ("telegram-bot", re.compile(r"\b\d{8,12}:[A-Za-z0-9_\-]{35}\b")),
    ("anthropic-key", re.compile(r"\bsk-ant-[A-Za-z0-9_\-]{20,}\b")),
    ("openai-key", re.compile(r"\bsk-[A-Za-z0-9]{20,}T3BlbkFJ[A-Za-z0-9]{20,}\b")),  # classic
    ("openai-proj", re.compile(r"\bsk-proj-[A-Za-z0-9_\-]{20,}\b")),                # new project keys
    ("npm-token", re.compile(r"\bnpm_[A-Za-z0-9]{36}\b")),
    ("pypi-token", re.compile(r"\bpypi-AgEIcHlwaS5vcmc[A-Za-z0-9_\-]{50,}\b")),
    ("discord-webhook", re.compile(
        r"https?://(?:ptb\.|canary\.)?discord(?:app)?\.com/api/webhooks/\d+/[A-Za-z0-9_\-/]+"
    )),
]

# Names that strongly suggest a person. Allows leading comment markers (#, //, *).
NAME_HINT_PATTERNS = [
    re.compile(
        r"^[\s#/*\-]*(?:作者|Author|By|by|Maintainer|Owner|Created\s+by)\s*[:：]?\s*"
        r"([一-龥]{2,4}|[A-Z][a-z]+\s+[A-Z][a-z]+)"
    ),
]

# Org/school name detection — we list common patterns and let the agent's
# review pass catch the rest. We don't auto-flag at danger level.
#
# Common false positives we filter out:
#   "MIT License" / "MIT许可证"  → MIT is an acronym for the license
#   "Microsoft YaHei" / "Microsoft Sans Serif"  → font name, not company attribution
#   "Google Maps SDK"            → legal SDK name, not personal employer mention
#   "Apple Color Emoji" / "AppleWebKit" / "AppleScript"  → system/framework names
#   "Stanford NLP" / "Berkeley DB" → library/tooling names
EXCLUDE_CONTEXT = (
    r"(?:\s+YaHei(?:UI)?"          # Microsoft YaHei UI
    r"|\s+Sans(?:\s+Serif)?"        # Microsoft Sans Serif
    r"|\s+Mahjong"                  # Microsoft Mahjong
    r"|\s+(?:Hei|Ya|Song|Kai|Yuan)(?:\s+UI)?"  # various CJK fonts
    r"|Color\s+Emoji"               # Apple Color Emoji
    r"|WebKit"                      # AppleWebKit
    r"|Script"                      # AppleScript
    r"|Music|Pay|News|TV\+|Store|Podcasts"   # Apple services
    r"|Maps|Fonts|Translate|Cloud|Ads|Analytics|Firebase"  # Google products
    r")"
)

# A line that looks like an attribution / signature line. org-name-hint only
# fires on these lines, so that "metadata" / "apple pie" in running prose
# never triggers a company-name hint. (real-name-hint is separately scoped by
# its own Author/Maintainer/... prefix in NAME_HINT_PATTERNS, so it needs no
# gate here.)
ATTRIBUTION_LINE = re.compile(
    r"^[\s#/*\-]*(?:作者|Author|Maintainer|Owner|Created\s+by|By|by)\s*[:：]?"
)
ORG_NAME_HINT = re.compile(
    r"(?<![A-Za-z0-9])(武汉大学|清华大学|北京大学|复旦大学|上海交通大学|浙江大学|中山大学|华中科技大学)"
    r"|(?<![A-Za-z0-9])(Wuhan\s+University|Tsinghua\s+University|Peking\s+University|Fudan\s+University)"
    r"|(?<![A-Za-z0-9])(Stanford\s+NLP|Berkeley\s+DB)"
    r"|(?<![A-Za-z0-9])(Microsoft|Google|Apple|Amazon|Meta|Tencent|Alibaba|Baidu|Bytedance|Huawei|NetEase|Meituan)(?!" + EXCLUDE_CONTEXT + r")",
)
# MIT is a special case: "MIT License" / "MIT协议" should not flag.
ORG_NAME_HINT_MIT = re.compile(
    r"(?<![A-Za-z0-9])MIT(?![A-Za-z0-9])",
)
MIT_FOLLOWED_BY_LICENSE = re.compile(
    r"MIT(?:\s*(?:License|许可证|协议|许可))",
)

# --------------------------------------------------------------------------- #
# Output dataclasses
# --------------------------------------------------------------------------- #

@dataclass
class Finding:
    category: str           # ai_trace_file | ai_trace_content | privacy_pattern | dangerous_file | large_file
    severity: str           # info | warn | danger
    path: str
    line: int | None = None
    pattern: str | None = None
    snippet: str | None = None
    size_bytes: int | None = None
    suggestion: str = ""
    count: int | None = None

# --------------------------------------------------------------------------- #
# Scanners
# --------------------------------------------------------------------------- #

def iter_files(root: Path) -> Iterable[Path]:
    """Yield files under root, skipping common build / VCS directories."""
    for dirpath, dirnames, filenames in os.walk(root):
        # Prune skip dirs in-place so os.walk skips them.
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS and not d.startswith(".venv")]
        for name in filenames:
            yield Path(dirpath) / name


def match_ai_trace_file(rel: str) -> bool:
    normalized = rel.replace("\\", "/")
    for pat in AI_TRACE_FILE_PATTERNS:
        # Match the full path, or the first path component (for directories)
        if pat.search(normalized):
            return True
        first_part = normalized.split("/")[0] if "/" in normalized else normalized
        if pat.search(first_part):
            return True
    return False


def match_dangerous_file(rel: str) -> bool:
    for pat in DANGEROUS_FILE_PATTERNS:
        if pat.search(rel):
            return True
    return False


def is_scannable(p: Path) -> bool:
    if p.suffix.lower() in SCANNABLE_EXTS:
        return True
    # Files without suffix that we still want to scan (Dockerfile, Makefile, etc.)
    if p.name in {"Dockerfile", "Makefile", "Rakefile", "Gemfile", "Procfile"}:
        return True
    return False


def scan_file_content(p: Path, rel: str) -> list[Finding]:
    """Read a file and run content patterns. Snippet is truncated to 200 chars."""
    try:
        if p.stat().st_size > MAX_SCAN_BYTES:
            return []  # Don't scan huge files for content
        raw = p.read_bytes()
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError:
            text = raw.decode("latin-1", errors="replace")
    except (OSError, PermissionError):
        return []

    findings: list[Finding] = []
    for n, line in enumerate(text.splitlines(), 1):
        findings.extend(scan_line(line, n, rel))
    return findings


# Patterns that should always be `danger` (secrets/keys) regardless of source.
_DANGER_PRIVACY = {
    "api-key", "jwt", "aws-key", "github-token",
    "aliyun-key", "tencent-key", "huawei-key",
    "stripe-live", "stripe-test", "slack-token", "telegram-bot",
    "anthropic-key", "openai-key", "openai-proj",
    "npm-token", "pypi-token", "discord-webhook",
    "id-card-cn", "bank-card",
}


def scan_line(line: str, line_no: int | str, rel: str) -> list[Finding]:
    """Run all content patterns on a single line. Shared by file & history scan."""
    findings: list[Finding] = []
    stripped = line.strip()[:200]

    # AI content (one match per line is enough)
    for pat, kind in AI_CONTENT_PATTERNS:
        if pat.search(line):
            findings.append(Finding(
                category="ai_trace_content",
                severity="warn",
                path=rel,
                line=line_no,
                pattern=kind,
                snippet=stripped,
                suggestion="删除该行或替换为非 AI 归属说明",
            ))
            break

    # Privacy (one match per line — we pick the first/loudest)
    for name, pat in PRIVACY_PATTERNS:
        m = pat.search(line)
        if m:
            # bank-card: reject all-same-digit strings (e.g. 1111111111111111)
            if name == "bank-card" and len(set(m.group())) == 1:
                continue
            if name == "email" and _is_safe_email(m.group()):
                continue
            if name in ("local-path-win", "local-path-unix") and _is_safe_path_user(m):
                continue
            if name == "ipv4-private" and _is_safe_private_ip(m.group()):
                continue
            findings.append(Finding(
                category="privacy_pattern",
                severity="danger" if name in _DANGER_PRIVACY else "warn",
                path=rel,
                line=line_no,
                pattern=name,
                snippet=stripped,
                suggestion=f"替换为占位符（如 `<{name.upper()}>`）或删除",
            ))
            break

    # Name hints
    m = NAME_HINT_PATTERNS[0].search(line)
    if m:
        findings.append(Finding(
            category="privacy_pattern",
            severity="info",
            path=rel,
            line=line_no,
            pattern="real-name-hint",
            snippet=stripped,
            suggestion="确认是否需要匿名化（取决于开源意图）",
        ))

    # Org hint: only on attribution lines (Author/Maintainer/...), so prose
    # words like "metadata" / "apple pie" never trigger it.
    if ATTRIBUTION_LINE.search(line):
        m = ORG_NAME_HINT.search(line)
        org_match = bool(m) or (
            bool(ORG_NAME_HINT_MIT.search(line))
            and not bool(MIT_FOLLOWED_BY_LICENSE.search(line))
        )
        if org_match:
            findings.append(Finding(
                category="privacy_pattern",
                severity="info",
                path=rel,
                line=line_no,
                pattern="org-name-hint",
                snippet=stripped,
                suggestion="确认是否需要匿名化（学校/公司）",
            ))

    return findings


def aggregate_info_findings(findings: list[Finding]) -> list[Finding]:
    """Merge info-severity findings sharing the same (path, pattern) into one.

    Non-info findings pass through unchanged. The merged finding keeps the
    first occurrence's line/snippet/suggestion and sets `count` to the number
    merged. Order: non-info findings keep original relative order; info
    findings are emitted at the position of their first occurrence.
    """
    result: list[Finding] = []
    seen: dict[tuple[str, str | None], int] = {}  # (path, pattern) -> index in result
    for f in findings:
        if f.severity != "info" or f.pattern is None:
            result.append(f)
            continue
        key = (f.path, f.pattern)
        if key in seen:
            idx = seen[key]
            result[idx].count = (result[idx].count or 1) + 1
        else:
            seen[key] = len(result)
            f_copy = Finding(**asdict(f))
            f_copy.count = 1
            result.append(f_copy)
    return result


def scan_history(root: Path, max_commits: int = 200) -> list[Finding]:
    """Run `git log -p` and scan every added/modified line for the same patterns.

    Reports findings tagged with `commit:<sha>` in the path so the agent can
    decide whether to amend/rewrite history.
    """
    if not (root / ".git").is_dir():
        return []

    try:
        proc = subprocess.run(
            ["git", "log", "--all",
             f"--max-count={max_commits}",
             "-p", "--no-color",
             "--pretty=format:---COMMIT %H %an <%ae> %s---"],
            cwd=str(root),
            capture_output=True, text=True, timeout=60,
            errors="replace",
        )
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError) as e:
        return [Finding(
            category="history_scan_error",
            severity="info",
            path="(history)",
            snippet=f"git log failed: {e}",
            suggestion="跳过历史扫描，文件扫描结果仍然有效",
        )]

    if proc.returncode != 0:
        return []

    findings: list[Finding] = []
    current_sha = "(no-commit)"
    current_author = ""
    current_file = ""
    hunk_line_no = 0

    for raw in proc.stdout.splitlines():
        if raw.startswith("---COMMIT "):
            # New commit header
            tail = raw[len("---COMMIT "):].rstrip("---")
            parts = tail.split(" ", 3)
            # parts: [sha, name+email, subject]
            current_sha = parts[0] if parts else "(?)"
            current_author = " ".join(parts[1:]) if len(parts) > 1 else ""
            current_file = ""
            hunk_line_no = 0
            continue

        if raw.startswith("diff --git "):
            # diff --git a/foo b/foo
            m = re.match(r"diff --git a/(.+?) b/(.+)", raw)
            current_file = m.group(2) if m else ""
            hunk_line_no = 0
            continue

        if raw.startswith("@@"):
            # @@ -old +new @@
            m = re.search(r"\+(\d+)", raw)
            if m:
                hunk_line_no = int(m.group(1))
            continue

        if not current_file or not raw:
            continue

        # Only scan added/changed lines, not context (context is just reflow)
        if not (raw.startswith("+") and not raw.startswith("+++")):
            if raw.startswith("-"):
                continue
            # Context line still increments hunk line number on the + side
            # (git diff shows context with leading space; we don't scan those)
            continue

        content = raw[1:]  # strip the leading '+'
        # Tag with commit + author so agent can see WHO added the secret
        rel_label = f"commit:{current_sha[:12]}:{current_file}:{hunk_line_no}"
        snippet = f"[{current_author}] {content.strip()[:180]}"

        for f in scan_line(content, hunk_line_no, rel_label):
            f.snippet = snippet
            f.suggestion = (
                f"考虑 amend/rebase 此 commit，或用 `git filter-repo` 重写历史"
            )
            findings.append(f)

        hunk_line_no += 1

    return findings


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

# --------------------------------------------------------------------------- #
# Self-test
# --------------------------------------------------------------------------- #

def _self_test() -> int:
    """Run built-in regression tests against synthetic fixtures.

    Returns 0 on success, 1 on failure. Stdout is human-readable.
    """
    import tempfile
    import shutil

    passed = 0
    failed = 0

    def check(label: str, actual: object, expected: object) -> None:
        nonlocal passed, failed
        if actual == expected:
            passed += 1
            print(f"  PASS  {label}")
        else:
            failed += 1
            print(f"  FAIL  {label}")
            print(f"        expected: {expected!r}")
            print(f"        actual:   {actual!r}")

    def check_pattern(pat_name: str, text: str, should_match: bool) -> None:
        """Check whether a privacy/content pattern matches text."""
        # Privacy patterns
        for name, pat in PRIVACY_PATTERNS:
            if name == pat_name:
                m = pat.search(text)
                matched = bool(m)
                # bank-card: reject all-same-digit strings (same logic as scan_line)
                if matched and name == "bank-card" and len(set(m.group())) == 1:
                    matched = False
                check(f"{pat_name} on {text!r:.40}", matched, should_match)
                return
        # AI content patterns — multiple patterns share the same kind,
        # so test ALL of them; any match counts as a hit.
        matched = False
        for pat, kind in AI_CONTENT_PATTERNS:
            if kind == pat_name and pat.search(text):
                matched = True
                break
        if any(kind == pat_name for _, kind in AI_CONTENT_PATTERNS):
            check(f"{pat_name} on {text!r:.40}", matched, should_match)
            return
        check(f"unknown pattern: {pat_name}", False, False)

    def check_scan_line(label: str, text: str, expected_patterns: set) -> None:
        """Run scan_line on text and compare the set of matched pattern names.

        expected_patterns is the set of Finding.pattern values expected.
        Empty set means the line should produce NO finding.
        """
        nonlocal passed, failed
        actual = {f.pattern for f in scan_line(text, 1, "test")}
        if actual == expected_patterns:
            passed += 1
            print(f"  PASS  {label}")
        else:
            failed += 1
            print(f"  FAIL  {label}")
            print(f"        expected patterns: {expected_patterns}")
            print(f"        actual patterns:   {actual}")

    print("Running self-test...")
    print()

    # --- Pattern unit tests ---
    print("[1] Pattern tests")

    # email
    check_pattern("email", "user@example.com", True)
    check_pattern("email", "not-an-email", False)

    # phone-cn
    check_pattern("phone-cn", "13812345678", True)
    check_pattern("phone-cn", "+86 138 1234 5678", True)
    check_pattern("phone-cn", "12345", False)

    # id-card-cn (18 digits)
    check_pattern("id-card-cn", "110101199003074518", True)
    check_pattern("id-card-cn", "1234567890", False)

    # bank-card: real card
    check_pattern("bank-card", "6222021234567890123", True)
    # bank-card: hex string (UUID) should NOT match
    check_pattern("bank-card", "550e8400e29b41d4a716", False)
    # bank-card: all-same-digit should NOT match
    check_pattern("bank-card", "1111111111111111", False)

    # api-key
    check_pattern("api-key", "api_key = 'abcdefghijklmnopqrst'", True)
    check_pattern("api-key", "api_key = 'short'", False)

    # local paths
    check_pattern("local-path-win", r"D:\Users\john\projects", True)
    check_pattern("local-path-unix", "/home/alice/.ssh/id_rsa", True)

    # cloud keys
    check_pattern("aws-key", "AKIAIOSFODNN7EXAMPLE", True)
    check_pattern("github-token", "ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghij", True)
    check_pattern("aliyun-key", "LTAIxxxxxxxxxxxx", True)
    check_pattern("anthropic-key", "sk-ant-api03-aaaaaaaaaaaaaaaaaaaaaaaa", True)

    # AI content
    check_pattern("ai-attribution", "Co-Authored-By: Claude <noreply@anthropic.com>", True)
    check_pattern("ai-attribution", "Generated with Claude Code", True)
    check_pattern("ai-leak", "<system-reminder>", True)
    check_pattern("ai-leak", "normal code line", False)

    print()
    print("[1b] org-name-hint attribution gating")
    # 正文词不应触发 org-name-hint
    for word in ["metadata", "metaphor", "apple pie", "viewport",
                 "und mit Liebe", "Google Maps SDK", "Microsoft YaHei",
                 "本项目采用MIT协议"]:
        check_scan_line(f"non-attribution: {word!r}", word, set())
    # 署名行应触发 org-name-hint
    check_scan_line("attribution: 张三 Tencent",
                    "Author: 张三 Tencent", {"real-name-hint", "org-name-hint"})
    check_scan_line("attribution: Apple Inc.",
                    "Author: Zhang San, Apple Inc.", {"real-name-hint", "org-name-hint"})
    check_scan_line("attribution: pure org",
                    "Maintainer: Alibaba", {"org-name-hint"})
    check_scan_line("attribution: MIT org", "Author: MIT", {"org-name-hint"})

    print()
    print("[1c] email whitelist")
    for addr in ["noreply@github.com", "user@example.com", "foo@test.com",
                 "admin@example.invalid"]:
        check_scan_line(f"safe email: {addr!r}", addr, set())
    # GitHub 平台域：占位 local 不报，真实用户名仍报（覆盖 github 域分支）
    check_scan_line("safe email github user", "user@github.com", set())
    check_scan_line("safe email noreply users.noreply",
                    "noreply@users.noreply.github.com", set())
    check_scan_line("real email github user",
                    "zhangsan@users.noreply.github.com", {"email"})
    # 真实邮箱仍报
    check_scan_line("real email .cn", "zhangsan@realcompany.cn", {"email"})
    check_scan_line("real email apple.com", "zhangsan@apple.com", {"email"})
    # 同行白名单邮箱 + 真手机号：邮箱不报、手机号仍报
    check_scan_line("mixed line keeps phone",
                    "contact: noreply@github.com 或 13812345678", {"phone-cn"})

    print()
    print("[1d] local-path whitelist")
    for p in ["/home/user/x", "/home/alice/.ssh", "C:\\Users\\user\\x"]:
        check_scan_line(f"safe path: {p!r}", p, set())
    check_scan_line("real path unix", "/home/zhangsan/x", {"local-path-unix"})
    check_scan_line("real path win", r"C:\Users\zhangsan\x", {"local-path-win"})
    # Windows 正斜杠路径由 local-path-unix 命中，捕获组同样取用户名段
    check_scan_line("safe path win fwdslash", "C:/Users/user/x", set())
    check_scan_line("real path win fwdslash", "C:/Users/zhangsan/x", {"local-path-unix"})

    print()
    print("[1e] ipv4-private whitelist")
    for ip in ["192.168.0.1", "192.168.1.1", "10.0.0.1", "10.0.0.2"]:
        check_scan_line(f"safe ip: {ip!r}", ip, set())
    check_scan_line("real private ip", "192.168.1.100", {"ipv4-private"})

    print()
    print("[1f] aggregate_info_findings")
    raw = [
        Finding(category="privacy_pattern", severity="info", path="a.py",
                line=1, pattern="org-name-hint", snippet="Author: Tencent"),
        Finding(category="privacy_pattern", severity="info", path="a.py",
                line=2, pattern="org-name-hint", snippet="Author: Alibaba"),
        Finding(category="privacy_pattern", severity="info", path="a.py",
                line=3, pattern="real-name-hint", snippet="Author: Zhang San"),
        Finding(category="privacy_pattern", severity="warn", path="a.py",
                line=4, pattern="email", snippet="real@x.cn"),
        Finding(category="privacy_pattern", severity="info", path="b.py",
                line=1, pattern="org-name-hint", snippet="Author: Baidu"),
    ]
    agg = aggregate_info_findings(raw)
    # info 按 (path,pattern) 聚合：a.py/org-name-hint 合并为1条 count=2
    a_org = [f for f in agg if f.path == "a.py" and f.pattern == "org-name-hint"]
    check("a.py org-name-hint aggregated to 1", len(a_org), 1)
    check("a.py org-name-hint count==2", a_org[0].count if a_org else None, 2)
    check("a.py org-name-hint keeps first line", a_org[0].line if a_org else None, 1)
    # real-name-hint 单条也走聚合路径（count=1）
    a_name = [f for f in agg if f.path == "a.py" and f.pattern == "real-name-hint"]
    check("a.py real-name-hint count==1", a_name[0].count if a_name else None, 1)
    # warn 不聚合，原样保留
    check("warn email not aggregated",
          sum(1 for f in agg if f.severity == "warn"), 1)
    # b.py 独立
    check("b.py org-name-hint present",
          sum(1 for f in agg if f.path == "b.py" and f.pattern == "org-name-hint"), 1)
    # 顺序不变性：info 在首次出现位置输出，非 info 原位保留
    check("order preserved",
          [(f.severity, f.pattern, f.line) for f in agg],
          [("info", "org-name-hint", 1), ("info", "real-name-hint", 3),
           ("warn", "email", 4), ("info", "org-name-hint", 1)])

    print()

    # --- File-level integration test ---
    print("[2] File scan integration test")

    tmpdir = Path(tempfile.mkdtemp(prefix="togithub_test_"))
    try:
        # Create test fixtures
        (tmpdir / ".env").write_text("DB_PASSWORD=supersecret1234567890\n")
        (tmpdir / "config.py").write_text(
            'API_KEY = "abcdefghijklmnop"\n'
            'AUTHOR: Zhang San\n'
            'url = "https://example.com"\n'
        )
        (tmpdir / "README.md").write_text(
            "# My Project\nCo-Authored-By: Claude\n"
        )
        (tmpdir / "CREDITS.md").write_text(
            "Author: Zhang San Tencent\n"
            "Author: Li Si Tencent\n"
            "Author: Wang Wu Tencent\n"
        )
        (tmpdir / ".claude").mkdir()
        (tmpdir / ".claude" / "memory.md").write_text("some memory")
        (tmpdir / "safe.txt").write_text("nothing sensitive here\n")

        # Run scanner
        findings = []
        seen_dirs: set[str] = set()
        for p in iter_files(tmpdir):
            rel = str(p.relative_to(tmpdir))
            try:
                sz = p.stat().st_size
            except OSError:
                continue
            if match_dangerous_file(rel):
                findings.append(Finding(
                    category="dangerous_file", severity="danger",
                    path=rel, suggestion="test",
                ))
            if match_ai_trace_file(rel):
                top = rel.split("/", 1)[0] if "/" in rel else rel
                if top not in seen_dirs:
                    seen_dirs.add(top)
                    findings.append(Finding(
                        category="ai_trace_file", severity="warn",
                        path=top, suggestion="test",
                    ))
                continue
            if is_scannable(p):
                findings.extend(scan_file_content(p, rel))

        # Aggregate info-severity hints (mirrors what main does), so this
        # integration test exercises the real scan -> aggregate path.
        findings = aggregate_info_findings(findings)

        cats = {}
        for f in findings:
            cats.setdefault(f.category, []).append(f)

        check(".env flagged as dangerous_file",
              "dangerous_file" in cats and any(f.path == ".env" for f in cats["dangerous_file"]),
              True)

        check(".claude/ flagged as ai_trace_file",
              "ai_trace_file" in cats and any(".claude" in f.path for f in cats["ai_trace_file"]),
              True)

        check("README.md ai_trace_content detected",
              "ai_trace_content" in cats and any("README.md" in f.path for f in cats["ai_trace_content"]),
              True)

        check("config.py api-key detected",
              "privacy_pattern" in cats and any("config.py" in f.path for f in cats["privacy_pattern"]),
              True)

        check("CREDITS.md org-name-hint aggregated to 1",
              sum(1 for f in findings if f.path == "CREDITS.md"
                  and f.pattern == "org-name-hint"), 1)
        cred = [f for f in findings if f.path == "CREDITS.md"
                and f.pattern == "org-name-hint"]
        check("CREDITS.md org-name-hint count==3",
              cred[0].count if cred else None, 3)

        check("safe.txt has no findings",
              not any("safe.txt" in f.path for f in findings),
              True)

    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)

    print()

    # --- Summary ---
    total = passed + failed
    print(f"Self-test complete: {passed}/{total} passed, {failed} failed.")
    return 0 if failed == 0 else 1


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def main() -> int:
    ap = argparse.ArgumentParser(description="Togithub pre-push scanner")
    ap.add_argument("root", nargs="?", help="project root directory")
    ap.add_argument("--exclude", action="append", default=[], help="glob to exclude (relative)")
    ap.add_argument("--scan-history", action="store_true",
                    help="also scan git history (git log -p) for secrets")
    ap.add_argument("--max-commits", type=int, default=200,
                    help="max commits to scan in history (default 200)")
    ap.add_argument("--history-only", action="store_true",
                    help="only scan history, skip file scan")
    ap.add_argument("--self-test", action="store_true",
                    help="run built-in regression tests and exit")
    args = ap.parse_args()

    if args.self_test:
        return _self_test()

    if not args.root:
        ap.error("root is required (or use --self-test)")

    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"error: not a directory: {root}", file=sys.stderr)
        return 1

    excludes = [re.compile(e.replace("*", ".*")) for e in args.exclude]

    findings: list[Finding] = []

    # File scan
    if not args.history_only:
        seen_dirs: set[str] = set()
        file_findings: list[Finding] = []
        for p in iter_files(root):
            rel = str(p.relative_to(root))

            if any(pat.search(rel) for pat in excludes):
                continue

            try:
                sz = p.stat().st_size
            except OSError:
                continue

            if sz > LARGE_FILE_BYTES:
                file_findings.append(Finding(
                    category="large_file",
                    severity="warn",
                    path=rel,
                    size_bytes=sz,
                    suggestion="考虑加入 .gitignore / git-lfs / 拆分",
                ))

            if match_dangerous_file(rel):
                file_findings.append(Finding(
                    category="dangerous_file",
                    severity="danger",
                    path=rel,
                    size_bytes=sz,
                    suggestion="绝不推送：加入 .gitignore 或改用环境变量",
                ))

            if match_ai_trace_file(rel):
                top = rel.split("/", 1)[0] if "/" in rel else rel
                if top not in seen_dirs:
                    seen_dirs.add(top)
                    file_findings.append(Finding(
                        category="ai_trace_file",
                        severity="warn",
                        path=top,
                        suggestion="删除整个目录/文件（AI 协作痕迹或开发过程文件）",
                    ))
                continue

            if is_scannable(p):
                file_findings.extend(scan_file_content(p, rel))

        findings.extend(aggregate_info_findings(file_findings))

    # History scan
    if args.scan_history or args.history_only:
        hist_findings = scan_history(root, max_commits=args.max_commits)
        # Normalize history info-finding paths from commit:<sha>:<file>:<line>
        # to commit:<sha>:<file> so multi-line hints in one file aggregate.
        for f in hist_findings:
            if f.severity == "info" and f.path.startswith("commit:"):
                parts = f.path.split(":")
                # parts: [commit, <sha>, <file>, <line>...]
                if len(parts) >= 3:
                    f.path = ":".join(parts[:3])
        findings.extend(aggregate_info_findings(hist_findings))

    # Build JSON output
    out = {
        "root": str(root),
        "summary": {
            "total": len(findings),
            "by_category": {},
            "by_severity": {},
        },
        "findings": [asdict(f) for f in findings],
    }
    for f in findings:
        out["summary"]["by_category"][f.category] = out["summary"]["by_category"].get(f.category, 0) + 1
        out["summary"]["by_severity"][f.severity] = out["summary"]["by_severity"].get(f.severity, 0) + 1

    json.dump(out, sys.stdout, indent=2, ensure_ascii=False)
    print()  # trailing newline
    return 0


if __name__ == "__main__":
    sys.exit(main())
